# Site settings
title: LWP ❤️ SZH
description: LWP & SZH Love House
keywords: Love, LWP, SZH
author: lwpszh
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://lwpszh.cn/" # the base hostname & protocol for your site
gems: [jekyll-paginate,jekyll-seo-tag,jekyll-sitemap]
paginate: 3
google_analytics: 'UA-XXXXXXX-X'
